//=============================================================================
// executor.v — EX Stage top-level execution unit (pure datapath)
//=============================================================================
// Pure combinational, no registers, no control-signal generation. All
// control comes from id_ex.v (already decoded in ID Stage) and is either
// consumed here (alu_opcode / alu_src_a / alu_src / branch_sel) or passed
// through unchanged to ex_mem.v.
//
// Unconditional parallel computation, gating at the consumer:
//   - alu.v (arith/bit/cmp), pc+4, pc+imm and JALR target all compute
//     every cycle regardless of instruction type.
//   - Whether a result takes effect is decided downstream: regfile write
//     by reg_write + wb_src (WB stage), PC update by branch_taken
//     (flow_ctrl.v). E.g. BEQ computes rs1==rs2 AND pc+imm in parallel;
//     when not taken, the adder output is simply discarded.
//
// JALR target is closed here: (rs1 + imm) & ~1, so flow_ctrl.v only
// consumes o_branch_taken / o_branch_target with no secondary decode.
//=============================================================================

`include "const_define.vh"
`include "alu_op_define.vh"
`include "opcode_define.vh"

module executor (
    // ---- Datapath inputs (from id_ex.v) ----
    input  wire [31:0] i_pc,           // current instruction PC
    input  wire [31:0] i_rs1_data,     // rs1 register value
    input  wire [31:0] i_rs2_data,     // rs2 register value / store data
    input  wire [31:0] i_imm,          // sign-extended immediate
    input  wire [ 4:0] i_rd_addr,      // destination register address

    // ---- Control bus (from id_ex.v, generated by decode.v) ----
    input  wire [ 3:0] i_alu_opcode,   // flat ALU operation code
    input  wire [ 1:0] i_alu_src_a,    // A-port select: rs1 / pc / zero
    input  wire        i_alu_src,      // B-port select: 0=rs2, 1=imm
    input  wire [ 1:0] i_branch_sel,   // branch type: none/cond/JAL/JALR
    input  wire        i_mem_read,     // mem read enable (passthrough)
    input  wire        i_mem_write,    // mem write enable (passthrough)
    input  wire [ 1:0] i_mem_width,    // mem access width (passthrough)
    input  wire        i_mem_sext,     // mem sign-extend (passthrough)
    input  wire [ 1:0] i_wb_src,       // writeback source select (passthrough)
    input  wire        i_reg_write,    // regfile write enable (passthrough)

    // ---- Datapath outputs (to ex_mem.v) ----
    output wire [31:0] o_alu_result,   // ALU result
    output wire [31:0] o_pc_plus4,     // link address (JAL/JALR → rd)
    output wire [31:0] o_rs2_data,     // store data (passthrough)
    output wire [ 4:0] o_rd_addr,      // destination register (passthrough)

    // ---- Control passthrough (to ex_mem.v) ----
    output wire        o_mem_read,     // mem read enable
    output wire        o_mem_write,    // mem write enable
    output wire [ 1:0] o_mem_width,    // mem access width
    output wire        o_mem_sext,     // mem sign-extend
    output wire [ 1:0] o_wb_src,       // writeback source select
    output wire        o_reg_write,    // regfile write enable

    // ---- Branch info (to flow_ctrl.v) ----
    output wire        o_branch_taken,  // branch/jump taken
    output wire [31:0] o_branch_target  // resolved jump target
);

    //---------------------------------------------------------------------
    // Operand selection MUX (alu_a / alu_b)
    //---------------------------------------------------------------------
    // alu_src_a: ALU_A_RS1(rs1) / ALU_A_PC(pc) / ALU_A_ZERO(0 — LUI)
    // alu_src:   0=rs2, 1=imm
    wire [31:0] alu_a;
    wire [31:0] alu_b;

    assign alu_a = (i_alu_src_a == `ALU_A_PC)   ? i_pc        :
                   (i_alu_src_a == `ALU_A_ZERO) ? `XLEN_ZERO  :
                                                  i_rs1_data;
    assign alu_b = i_alu_src ? i_imm : i_rs2_data;

    //---------------------------------------------------------------------
    // Parallel computation units — always active, gating at consumer
    //---------------------------------------------------------------------
    wire [31:0] pc_plus4;      // pc+4 unit:   link address for JAL/JALR
    wire [31:0] pc_plus_imm;   // target adder: JAL / BRANCH target
    wire [31:0] jalr_target;   // JALR unit:    (rs1+imm) & ~1
    wire [31:0] alu_result;    // ALU:          arith / bit / cmp

    assign pc_plus4    = i_pc + `PC_INCREMENT;
    assign pc_plus_imm = i_pc + i_imm;
    assign jalr_target = (i_rs1_data + i_imm) & `PC_ALIGN_MASK;

    alu u_alu (
        .i_a      (alu_a),
        .i_b      (alu_b),
        .i_opcode (i_alu_opcode),
        .o_result (alu_result)
    );

    //---------------------------------------------------------------------
    // Branch Unit — zero secondary decode
    //---------------------------------------------------------------------
    // branch_sel: BRANCH_NONE / BRANCH_COND (taken = compare result) /
    //             BRANCH_JAL / BRANCH_JALR (taken = 1)
    assign o_branch_taken = (i_branch_sel != `BRANCH_NONE) &&
                            ((i_branch_sel == `BRANCH_COND) ? alu_result[0]
                                                            : 1'b1);

    assign o_branch_target = (i_branch_sel == `BRANCH_JALR) ? jalr_target
                                                            : pc_plus_imm;

    //---------------------------------------------------------------------
    // Datapath outputs
    //---------------------------------------------------------------------
    assign o_alu_result = alu_result;
    assign o_pc_plus4   = pc_plus4;
    assign o_rs2_data   = i_rs2_data;
    assign o_rd_addr    = i_rd_addr;

    //---------------------------------------------------------------------
    // Control passthrough — pure wire, no logic
    //---------------------------------------------------------------------
    assign o_mem_read   = i_mem_read;
    assign o_mem_write  = i_mem_write;
    assign o_mem_width  = i_mem_width;
    assign o_mem_sext   = i_mem_sext;
    assign o_wb_src     = i_wb_src;
    assign o_reg_write  = i_reg_write;

endmodule
